#!/bin/bash # Never actually run directly, helps syntax highlighter though
# .bash_profile

if [ -f /etc/profile ]; then
    . /etc/profile
fi

function addtopath
{
    if ! echo ${PATH} | /bin/grep -q "$1" ; then
        PATH=${1}:${PATH}
    fi
}

# User specific environment and startup programs
addtopath $HOME/bin
addtopath $HOME/.local/bin
export PATH

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

