#!/bin/bash # Never actually run directly, helps syntax highlighter though
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs

# Google AppEngine SDK
PATH="$HOME/Apps/google_appengine:$PATH"

PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export PATH

