---

# Ansible playbook to install dotfiles
#
# DOTFILE INSTALLATION
# 1. Requires ansible installed:
#      [user@host ~]$ pip install ansible
# 2. Clone this repo to a convenient location:
#      [user@host ~]$ git clone dotfiles ~/.dotfiles
# 3. Run with:
#      [user@host dotfiles]$ ansible-playbook --connection=local --inventory-file=localhost, install.yml
#    NB: the , after localhost is required
# 4. Create a branch for each host's customisations (can be merged to
#    other branches)
#      [user@host ~]$ git checkout -b hostname
#

- hosts: localhost

  vars:

    dotfiles:
      - source: bashrc
        dest: .bashrc
      - source: bash_profile
        dest: .bash_profile
      - source: bash_logout
        dest: .bash_logout
      - source: gitconfig
        dest: .gitconfig
      - source: vimrc
        dest: .vimrc
      - source: conkyrc
        dest: .conkyrc
      - source: conky.desktop
        dest: .config/autostart/conky.desktop

  tasks:

    - name: INSTALL DOTFILES | Link New Dotfiles
      file: state=link force=yes src={{ ansible_env.PWD }}/dotfiles/{{ item.source }} dest=~/{{ item.dest }}
      with_items: dotfiles

    - name: CONKY | Install Conky
      yum: state=present name=conky
      sudo: '"{{ ansible_user_id }}" != "root"'
      ignore_errors: yes

    - name: INSTALL VIM PLUGINS | Pre-requisite RPMs
      yum: state=present name={{ item }}
      sudo: '"{{ ansible_user_id }}" != "root"'
      ignore_errors: yes
      with_items:
        - vim-enhanced
        - python-pip

    - name: INSTALL VIM PLUGINS | Pre-requisite Python Modules
      pip: state=present name={{ item }}
      sudo: '"{{ ansible_user_id }}" != "root"'
      ignore_errors: yes
      with_items:
        - jedi
        - pylint
        - pep8

    - name: INSTALL VIM PLUGINS | Vim Bundle Directory
      file: state=directory path=~/.vim/bundle

    - name: INSTALL VIM PLUGINS | Vundle Plugin Manager
      git: repo="https://github.com/gmarik/vundle.git"
           dest=~/.vim/bundle/vundle
      register: vundle_cloned

    - name: INSTALL VIM PLUGINS | Install Vundle Bundles
      shell: "echo | vim -f +BundleInstall +qall"
      when: vundle_cloned | changed

    - name: DIRS | Github
      file: state=directory path=~/Code/github.com

    - name: DIRS | Gists
      file: state=directory path=~/Code/gist.github.com

    - name: DIRS | Local
      file: state=directory path=~/Code/{{ ansible_fqdn }}

    - name: SSH | Check Key
      shell: "ls ~/.ssh/id_rsa"
      ignore_errors: yes
      register: ssh_key
      changed_when: ssh_key.rc != 0

    - name: SSH | Make dir
      file: state=directory path=~/.ssh mode=0700
      when: ssh_key | changed

    - name: SSH | Generate Key
      shell: "ssh-keygen -N '' -t rsa -f ~/.ssh/id_rsa"
      when: ssh_key | changed

